- build.gradle
- src/main/java/com/firefighter/aenitto/members/domain/Member.java
- src/test/resources/application.yml
- test의 app.yml h2 inmem으로 변경
- Member 엔티티의 id의 pg-uuid 설정 제거
- hibernate-core 디펜던시 제거
> [Fix] 테스트환경 h2로 변경 / Member 엔티티 수정

- src/main/java/com/firefighter/aenitto/common/exception/room/RoomErrorCode.java
- src/main/java/com/firefighter/aenitto/common/exception/room/RoomNotParticipatingException.java
- src/main/java/com/firefighter/aenitto/common/response/CursorPagination.java
- src/main/java/com/firefighter/aenitto/common/response/LinkRelation.java
- src/main/java/com/firefighter/aenitto/common/response/PaginatedResponse.java
- src/main/java/com/firefighter/aenitto/members/domain/Member.java
- src/main/java/com/firefighter/aenitto/rooms/controller/RoomController.java
- src/main/java/com/firefighter/aenitto/rooms/domain/MemberRoom.java
- src/main/java/com/firefighter/aenitto/rooms/domain/Room.java
- src/main/java/com/firefighter/aenitto/rooms/domain/RoomState.java
- src/main/java/com/firefighter/aenitto/rooms/dto/response/GetRoomStateResponse.java
- src/main/java/com/firefighter/aenitto/rooms/dto/response/ParticipatingRoomsResponse.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepository.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepositoryImpl.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomService.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
- src/test/java/com/firefighter/aenitto/common/exception/ExceptionTest.java
- src/test/java/com/firefighter/aenitto/members/MemberFixture.java
- src/test/java/com/firefighter/aenitto/rooms/RoomFixture.java
- src/test/java/com/firefighter/aenitto/rooms/controller/RoomControllerTest.java
- src/test/java/com/firefighter/aenitto/rooms/dto/RoomResponseDtoBuilder.java
- src/test/java/com/firefighter/aenitto/rooms/repository/RoomRepositoryImplTest.java
- src/test/java/com/firefighter/aenitto/rooms/service/RoomServiceTest.java
> [Feat] 방 상태 조회 api

- BOOT-INF/classes/static/docs/html5/index.html
- src/main/resources/application.yml
- src/main/resources/data.sql
- src/main/resources/static/docs/index.html
- src/test/java/com/firefighter/aenitto/members/integration/MemberIntegrationTest.java
- src/test/resources/application.yml
> [Fix] socialId -> social_id로 변경

- src/main/java/com/firefighter/aenitto/common/exception/mission/MissionAlreadySetException.java
- src/main/java/com/firefighter/aenitto/common/exception/mission/MissionEmptyException.java
- src/main/java/com/firefighter/aenitto/common/exception/mission/MissionErrorCode.java
- src/main/java/com/firefighter/aenitto/missions/domain/CommonMission.java
- src/main/java/com/firefighter/aenitto/missions/domain/IndividualMission.java
- src/main/java/com/firefighter/aenitto/missions/domain/MissionType.java
- src/main/java/com/firefighter/aenitto/missions/repository/MissionRepository.java
- src/main/java/com/firefighter/aenitto/missions/repository/MissionRepositoryImpl.java
- src/main/java/com/firefighter/aenitto/missions/service/MissionService.java
- src/main/java/com/firefighter/aenitto/missions/service/MissionServiceImpl.java
- src/main/java/com/firefighter/aenitto/rooms/domain/MemberRoom.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepository.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepositoryImpl.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
- src/test/java/com/firefighter/aenitto/missions/CommonMissionFixture.java
- src/test/java/com/firefighter/aenitto/missions/MissionFixture.java
- src/test/java/com/firefighter/aenitto/missions/repository/MissionRepositoryTest.java
- src/test/java/com/firefighter/aenitto/missions/service/MissionServiceTest.java
- src/test/java/com/firefighter/aenitto/rooms/domain/MemberRoomTest.java
- src/test/java/com/firefighter/aenitto/rooms/repository/RoomRepositoryImplTest.java
- Repo
- 랜덤 미션 가져오기 
- 특정 일자의 공통 미션 가져오기 
- Service
- 특정 일자의 공통미션 세팅하기
> [Feat] 미션 관련 Repo, Service layer 코드 

- BOOT-INF/classes/static/docs/html5/index.html
- src/docs/asciidoc/index.adoc
- src/main/resources/static/docs/index.html
- src/test/java/com/firefighter/aenitto/rooms/controller/RoomControllerTest.java
Auth 헤더 테스트 코드에 적용하고 rest doc에도 적용.
> [Docs] Authorization Header Rest Docs에 추가 (#53)

- BOOT-INF/classes/static/docs/html5/index.html
- src/main/java/com/firefighter/aenitto/common/utils/RoomComparator.java
- src/main/java/com/firefighter/aenitto/rooms/controller/RoomController.java
- src/main/java/com/firefighter/aenitto/rooms/domain/RoomState.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepository.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepositoryImpl.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomService.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
- src/main/resources/static/docs/index.html
- src/test/java/com/firefighter/aenitto/common/utils/RoomComparatorTest.java
- src/test/java/com/firefighter/aenitto/rooms/RoomFixture.java
- src/test/java/com/firefighter/aenitto/rooms/controller/RoomControllerTest.java
- src/test/java/com/firefighter/aenitto/rooms/integration/RoomIntegrationTest.java
- src/test/java/com/firefighter/aenitto/rooms/service/RoomServiceTest.java
- src/test/resources/room-getParticipatingRooms.sql
- Cursor Pagination에서 (진행 상태, 최신순) 으로 정렬
> [Feat] 참여 중인 방 조회 수정 (#62) 

- README.md
> [Docs] 애니또 서버 리드미 작성 (#87)

- src/main/resources/application.yml
- src/test/java/com/firefighter/aenitto/message/integration/MessageIntegrationTest.java
- src/test/java/com/firefighter/aenitto/rooms/integration/RoomIntegrationTest.java
- src/test/java/com/firefighter/aenitto/rooms/repository/RelationShipRepositoryImplTest.java
- src/test/resources/application.yml
- src/test/resources/data.sql
- src/test/resources/relation.sql
- src/test/resources/room.sql
- src/test/resources/sql/api/room-getParticipatingRooms.sql
- 해당 pr 코드로 고친건 아니고 rds에 있던 data row들 ddl 설정 create로 한번 싹다 drop 하니까 에러는 해결됨.
- 아마 마이그레이션 문제였었던듯...
- 여기 pr에서는 test 환경에서 h2 mode = PostgreSQL 로 설정했을 때 나던 오류 수정함.
> [Hotfix] PostgreSQL 내부에러

- src/main/java/com/firefighter/aenitto/common/utils/SqlPath.java
- src/main/java/com/firefighter/aenitto/missions/service/MissionService.java
- src/main/java/com/firefighter/aenitto/missions/service/MissionServiceImpl.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
- src/test/java/com/firefighter/aenitto/rooms/integration/RoomIntegrationTest.java
- src/test/java/com/firefighter/aenitto/rooms/service/RoomServiceTest.java
- src/test/resources/sql/api/room-participate.sql
#105 
- RoomService, MissionService 코드 수정 
- RoomIntegrationTest 코드 수정
> [Feat] 방 참여할 때 개별 미션 설정해주기 

- src/main/java/com/firefighter/aenitto/AenittoApplication.java
- src/main/java/com/firefighter/aenitto/common/scheduler/SchedulerService.java
- src/main/java/com/firefighter/aenitto/rooms/domain/Room.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepository.java
- src/main/java/com/firefighter/aenitto/rooms/repository/RoomRepositoryImpl.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomService.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
- src/test/java/com/firefighter/aenitto/rooms/domain/RoomTest.java
- src/test/java/com/firefighter/aenitto/rooms/service/RoomServiceTest.java
#83 
- 23시 55분마다 다음날의 개별미션, 다음날의 공통미션 설정
- 00시 00분마다 endDate가 지난 방은 POST로 상태 변경.
> [Feat] Spring Scheduler 적용

- src/main/java/com/firefighter/aenitto/common/exception/room/AdminCannotExitRoomException.java
- src/main/java/com/firefighter/aenitto/common/exception/room/RoomErrorCode.java
- src/main/java/com/firefighter/aenitto/common/utils/SqlPath.java
- src/main/java/com/firefighter/aenitto/rooms/controller/RoomController.java
- src/main/java/com/firefighter/aenitto/rooms/repository/MemberRoomRepository.java
- src/main/java/com/firefighter/aenitto/rooms/repository/MemberRoomRepositoryImpl.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomService.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
- src/test/java/com/firefighter/aenitto/rooms/controller/RoomControllerTest.java
- src/test/java/com/firefighter/aenitto/rooms/integration/RoomIntegrationTest.java
- src/test/java/com/firefighter/aenitto/rooms/repository/MemberRoomRepositoryTest.java
- src/test/java/com/firefighter/aenitto/rooms/service/RoomServiceTest.java
- src/test/resources/sql/api/exit-room.sql
#114 
- MemberRoomRepository, RoomService, RoomController 구현
- MemberRoomRepository, RoomService, RoomController, RoomIntegration 테스트
> [Feat] 방 나가기 API 

- src/main/java/com/firefighter/aenitto/common/scheduler/SchedulerService.java
> [Chore] scheduler에 로그 남기기

- BOOT-INF/classes/static/docs/html5/index.html
- src/main/java/com/firefighter/aenitto/messages/dto/response/MessageResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/firefighter/aenitto/message/MessageFixture.java
- src/test/java/com/firefighter/aenitto/message/controller/MessageControllerTest.java
- src/test/java/com/firefighter/aenitto/message/service/MessageServiceImplTest.java
- src/test/resources/sql/message/memories.sql
- src/test/resources/sql/message/message.sql
- src/test/resources/sql/message/receivedMessage.sql
- src/test/resources/sql/message/sentMessage.sql
약간 자면서 코드 적고 있는거 같아서 이상한 코드 있을 수도 있어여.. 가차없는 리뷰 부탁
> [Chore] add createdDate message response

- build.gradle
- dependency 변경 
- 추가 원인은 wiki에 추가 하겠습니다
> [Bugfix] change asciidoctor dependency

- src/main/java/com/firefighter/aenitto/rooms/dto/request/UpdateRoomRequest.java
- PUT 
- 최소인원 validation 5인 -> 4인
> [Feat] 애니또 방 수정 API 변경 (#144)

- build.gradle
- src/main/java/com/firefighter/aenitto/config/SecurityConfig.java
- src/main/resources/static/docs/index.html
- src/test/java/com/firefighter/aenitto/common/annotation/validation/CustomDateValidatorTest.java
> [Refactor] 문서 접근 권한 변경

- src/main/java/com/firefighter/aenitto/common/postConstruct/PostConstructDailyService.java
@PostConstruct 어노테이션 사용하여 재시작 시
- 개별/공통 미션 설정 안되어있다면 재설정
- 끝나지 않은 방 끝내기.
> [Feat] 서버 재시작시 미션 설정 (#169)

- .github/ISSUE_TEMPLATE/aenitto-issue-template.md
- README.md
> convention 업데이트

- src/main/java/com/firefighter/aenitto/common/log/RequestLoggingFilter.java
- src/main/java/com/firefighter/aenitto/config/LoggingFilterConfig.java
> request 로깅 기능 추가

- src/main/java/com/firefighter/aenitto/messages/service/MessageServiceImpl.java
> 마니또가 발송한 메시지 도착 알림의 제목을 올바르게 수정

- .github/workflows/build.yml
> build workflow 추가

- src/main/java/com/firefighter/aenitto/missions/controller/CommonMissionController.java
- src/main/java/com/firefighter/aenitto/missions/domain/Mission.java
- src/main/java/com/firefighter/aenitto/missions/dto/response/UpdateRequest.java
- src/main/java/com/firefighter/aenitto/missions/dto/response/UpdateResponse.java
- src/main/java/com/firefighter/aenitto/missions/service/MissionService.java
- src/main/java/com/firefighter/aenitto/missions/service/MissionServiceImpl.java
> 미션 수정 api 추가

- src/main/java/com/firefighter/aenitto/auth/service/AuthServiceImplV1.java
- src/main/java/com/firefighter/aenitto/members/controller/MemberController.java
- src/main/java/com/firefighter/aenitto/members/domain/Member.java
- src/main/java/com/firefighter/aenitto/members/service/MemberService.java
- src/main/java/com/firefighter/aenitto/members/service/MemberServiceImpl.java
- src/main/java/com/firefighter/aenitto/missions/domain/IndividualMission.java
- src/main/java/com/firefighter/aenitto/rooms/domain/Relation.java
- src/main/java/com/firefighter/aenitto/rooms/domain/Room.java
- src/main/java/com/firefighter/aenitto/rooms/repository/MemberRoomRepository.java
- src/main/java/com/firefighter/aenitto/rooms/service/RoomServiceImpl.java
> 멤버 탈퇴 기능 추가

- src/main/java/com/firefighter/aenitto/auth/service/AuthServiceImplV1.java
- src/main/java/com/firefighter/aenitto/auth/service/AuthServiceImplV2.java
- src/main/java/com/firefighter/aenitto/members/controller/MemberController.java
- src/main/java/com/firefighter/aenitto/members/domain/Member.java
- src/main/java/com/firefighter/aenitto/members/service/MemberService.java
- src/main/java/com/firefighter/aenitto/rooms/domain/Room.java
> Fix member withdrawl org.hibernate.LazyInitializationException

- build.gradle
- src/main/java/com/firefighter/aenitto/config/WebClientConfig.java
> Fix propertySourcesPlaceholderConfigurer

- .github/workflows/deploy.yml
> Fix deploy job name in github actions

- src/main/java/com/firefighter/aenitto/rooms/domain/Relation.java
- src/main/java/com/firefighter/aenitto/rooms/domain/Room.java
> Fix duplicate key value violates unique constraint "relation_pkey" #238

- src/main/java/com/firefighter/aenitto/auth/controller/AuthControllerV2.java
- src/main/java/com/firefighter/aenitto/auth/service/AuthServiceImplV2.java
> 회원탈퇴한 사람이 로그인할 시 회원가입한 사람과 동일한 Response를 반환하도록 변경 #246

- src/main/java/com/firefighter/aenitto/members/controller/MemberController.java
- src/main/java/com/firefighter/aenitto/members/domain/Member.java
> 회원탈퇴 시 기존 닉네임을 null로 변경

- src/main/java/com/firefighter/aenitto/auth/service/AuthServiceImplV2.java
> isNewMember 프로퍼티에 정상적인 값이 들어가도록 조건문 수정

- .github/workflows/build.yml
- .github/workflows/deploy.yml
> github actions 수동 트리거 추가

- .github/workflows/deploy.yml
> deploy.yml의 env를 secrets로 변경

- src/main/java/com/firefighter/aenitto/missions/domain/IndividualMission.java
> Change IndividualMission GenerationType AUTO to SEQUENCE

- src/main/java/com/firefighter/aenitto/rooms/domain/Room.java
> 회원탈퇴시 이미 종료된 방은 탈퇴하지 않도록 변경
